id: P000774
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16557
  title: གླུ་འབུམ་པོ་ཏི་དགུ་སྒྲིལ། སྲིད་པའི་གནའ་སྒྲུང་རིང་མོ།
  author: ''
  volumes:
    17144fe41dbb4a2db8b7efe41f078da7:
      image_group_id: I2PD18041
      title: ''
      volume_number: 1
      total_pages: 556
      base_file: v001.txt
    3419005eb8784648a722ded01b584e5c:
      image_group_id: I2PD18042
      title: ''
      volume_number: 2
      total_pages: 588
      base_file: v002.txt
